# Site
name: 'iOS Junkie'
description: 'A blog by an iOS developer who created Laundry City'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/blog'
disqus: 'iosjunkie'
email: 'zoom.flux@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Gems
gem: [jekyll-admin]
  
authors:
    jules:
      name:           Jules Lee
      site:           https://iosjunkie.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Jules, the author of iOS Junkie. I hope you like my blog!"
      email:          zoom.flux@gmail.com
      facebook:        https://facebook.com/mr.jules.lee
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jules
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]