name: iOS Junkie
description: Simplifying complex instructions, tutorials, and a little bit more on the iOS Swift stuff.
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: /blog
disqus: iosjunkie
email: zoom.flux@gmail.com
include:
  - _pages
permalink: '/:title/'
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
gem:
  - jekyll-admin
authors:
  jules:
    name: Jules Lee
    site: 'https://iosjunkie.github.io'
    avatar: /assets/images/avatar1.jpg
    bio: >-
      Hi, I am Jules, the author of iOS Junkie. Simplifying complex instructions
      from the internet.
    email: zoom.flux@gmail.com
    facebook: 'https://facebook.com/mr.jules.lee'
defaults:
  - scope:
      path: _posts
    values:
      layout: post
      author: jules
      avatar: /assets/images/avatar1.jpg
  - scope:
      path: _pages
    values:
      layout: page
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
  - README.markdown
  - package.json
  - grunt.js
  - Gruntfile.js
  - Gruntfile.coffee
  - node_modules
