---
title: Blog
timezone: UTC+8
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: jules
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
name: FlutterGeek
future: true
description: Demystifying complex instructions, tutorials, and a little bit more geared toward mobile development in Flutter.
  components work.
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: "/blog"
url: http://fluttergeek.com
disqus: fluttergeek
email: zoom.flux@gmail.com
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
gem: 
authors:
  jules:
    name: Jules Lee
    site: https://fluttergeek.com
    avatar: "/assets/images/avatar1.jpg"
    bio: Hi, I am Jules, the author of FlutterGeek. Demystifying complex instructions
      from the internet.
    email: zoom.flux@gmail.com
    facebook: https://facebook.com/mr.jules.lee
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
paginate: 10
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
- Gemfile
- Gemfile.lock
- vendor/bundle/